apiVersion: v1
kind: Pod
metadata:
  name: nginx-readonlyrootfilesystem
  labels:
    app: nginx-readonlyrootfilesystem
spec:
  containers:
  - name: nginx
    image: nginx
    securityContext:
      readOnlyRootFilesystem: true
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
