apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAutomountServiceAccount
metadata:
  name: automount-service-account
spec:
  match:
    excludedNamespaces: {{ .Values.excludedNamespaces }}
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
